os:
  - linux
  - osx

osx_image: xcode61

language: cpp

before_script:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y llvm-3.4 llvm-3.4-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm && brew link --force llvm; fi
  
compiler:
  - clang++
  - g++

script:
    - g++ -O2 -o sokoban sokoban.cpp
    - clang++ -o sokoban sokoban.cpp
  
branches:
  only:
    - master  
