version: 0.5.0.{build}

branches:
    only:
        - master

os: Windows Server 2012 R2

clone_folder: c:\projects\gogosokoban

#platform: Any CPU
#configuration: Debug

install:
    # by default, all script lines are interpreted as batch

# scripts to run before build
#before_build:

build:
    sources: sokoban.cpp      # path to Visual Studio solution or project

#after_build:
